apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-app
          env:
            - name: ENV
              value: dev
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "20m"
              memory: "64Mi"
