apiVersion: v1
kind: Service
metadata:
  name: go-deployment
spec:
  selector:
    app.kubernetes.io/name: go-deployment
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP