apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
  namespace: tekton-ci
  annotations:
    tekton.dev/git-0: gitlab.com  # gitlab url
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAzrZ6V1IKrJauE/FyrSpO4H9peuIjjEGtn0Wy/K0bmIwlb/OPjlZR
    jRDpB/GNVbtL58Z/pgUKc2bje28fvUvdbz6E1DVe9/oCL5aBka/jWXXDEr8oJAEuSpPLR3
    99wDLufo4LNV5jJkvCLFvBbHbc8RoPkJ22FE3e9BNslfsUCBvl2Rv1Gc5XeWveWM3nPUPb
    vOMhZpGcqQR6ZKWsvIU3JCPqWQnaF8nXgyGT0MIlnjPnaIpFLHSrOsT1Hmz6pD7HD/zecQ
    VZyZRv5bQ+jvrSpwJbQvJ5i3xFwEPBaTn75gC2D6JxQpTaPeG0DtL7wGj3t712dg0D382X
    mUvR4h08S9E5/XbSS3NZZGLS8YVBNYmuSvFNOvbdkLsevyfyf+svFgPxEcuMx5q7sRJTkK
    6RKG4uT0UiGs44AT3TjSl1RfDQuK+GrbRKZfS1z/HvWtPeK9fG/KFOIkNozLHfywkK359T
    eWkqZDvNbKAL77KuVxRhVqYhphNXg20eI2WigO0y6ujBKlKPy9aP8SIuz097P/PopX1JvU
    YkGwQNzHYKCKDZFBy9wC+bGcrirPHlzTMO9jfXd2hwGo2Zs3GJf0/rcNVVjQF8IFFOH2QS
    ILdF/3CGuULM2YwSHTm7qhkudfCPgS3ok58LNg0tgYpXQkrXbW31SdO6Hp7DTUpfcQtCXE
    UAAAdAJGAbXCRgG1wAAAAHc3NoLXJzYQAAAgEAzrZ6V1IKrJauE/FyrSpO4H9peuIjjEGt
    n0Wy/K0bmIwlb/OPjlZRjRDpB/GNVbtL58Z/pgUKc2bje28fvUvdbz6E1DVe9/oCL5aBka
    /jWXXDEr8oJAEuSpPLR399wDLufo4LNV5jJkvCLFvBbHbc8RoPkJ22FE3e9BNslfsUCBvl
    2Rv1Gc5XeWveWM3nPUPbvOMhZpGcqQR6ZKWsvIU3JCPqWQnaF8nXgyGT0MIlnjPnaIpFLH
    SrOsT1Hmz6pD7HD/zecQVZyZRv5bQ+jvrSpwJbQvJ5i3xFwEPBaTn75gC2D6JxQpTaPeG0
    DtL7wGj3t712dg0D382XmUvR4h08S9E5/XbSS3NZZGLS8YVBNYmuSvFNOvbdkLsevyfyf+
    svFgPxEcuMx5q7sRJTkK6RKG4uT0UiGs44AT3TjSl1RfDQuK+GrbRKZfS1z/HvWtPeK9fG
    /KFOIkNozLHfywkK359TeWkqZDvNbKAL77KuVxRhVqYhphNXg20eI2WigO0y6ujBKlKPy9
    aP8SIuz097P/PopX1JvUYkGwQNzHYKCKDZFBy9wC+bGcrirPHlzTMO9jfXd2hwGo2Zs3GJ
    f0/rcNVVjQF8IFFOH2QSILdF/3CGuULM2YwSHTm7qhkudfCPgS3ok58LNg0tgYpXQkrXbW
    31SdO6Hp7DTUpfcQtCXEUAAAADAQABAAACAQCU0MAAzzqKB6xpBSEG03eXnYKFifoHhl0F
    VftGdyVvzC1DjHfkA/aP9QWex2J1vvIleTz6e5SLgh3xBg42jEBtTvf3gjjNk3oxYkwDYz
    nsdKAshdvTF9qIrB/jaEBStxgFmiMtl7cPoei3YJM+j8/970IXXcLwmSMSWk2JKAnC0LrH
    c54fpvJIosSe8BUygQDX2jh4jAnZkDTA8pkJ22nYJdcXpMUS7Seu6uRsnOjSHRHSrACiwZ
    doJtVEwzYqOlu7AdPuT+jU+30XRIzpCF/RBhxHdSLVrXDVurGqHKlha0+mr86UHW+Er1Ge
    fnvpiGgWKlr3H+WTIIKsRO5jt6Jos08WA0Wlod/NtbIbMcu5h680wrqv7DcS3en2bVCViU
    Ham7jTnea35OshKTKhywCiNjKg6hzeNiD1JKjZGAIU7xbNd6H5JjO61hSVqKBg+QWId+J7
    2jnFH0FogBPKQexh+sg8it3KkuFumYG8vg9fvE934Bq2o7WyK2k+zBDdjlweiTJ9cQTwNl
    e4NGc9kB2Ah61JXha9flx876PVIKY9TNy6aQRNC6PHRMRbpFiYa2UzueZc2OKm0m70u35y
    a03ulzrAyWDTxqptnjQXRwByJUW3i1LAQ3aiFwJnjCDzP/zH4JpTQQR2+r0yDjODboC2iy
    Rg4B8yszaUrQJS94N1AQAAAQEAhYO5D0Giuj0SXLQq/mWHhxhM/Ll4HOlvfYn9uczkeW8n
    nXeuN1r8Dqhl0u3fWOiZZe8hk1GXmk6E+ybZ5nhq0dT0c8/V9H+hzcY1auUjKnlecfBKP8
    Qi7U+kKtpe5UTrLQzzvlzGjAz4f0irRUBJ1YoD7twMdJmh4zyXcB/By/baDRxW7JAQlyoQ
    wlc9vQb2quirAGsWN2UlRuNWm+3+68fc//ZEqHotwOTlg4WprXbFDaMWe3ZmlxMLEqC05H
    l1ryDjT0/S8DwVNMPixjVGheEx2RV7BubP2M/7+crgvhSsLFZ3gTJc6aM4tRza4umHYviH
    RBUfmtiTwiAg0y8cRgAAAQEA7w44Ae/PyWaxcPvSDS/JaABW80KxmGaBYZVobc4jgJ2BOE
    6O0xB315uCIWngjH1nLgmVZLwurwb/ZMoscguL5dM4ITes3DAOpcGzZzc3p4RJfj8qlF9w
    ygAFLX2PnYRfB8w6N2ZbqND5VNY27/TW8E2VwSTtcEf99ZGh2LvcQ+MupiY0Untc5B7vr/
    qlvbIZN0j1tobNjZlzUmwzo4N5mMaRjc6zeHLtY2DtnsSXk+taRNCivsIwWKULVCzlgsjM
    T+ByBVmu3cpRaAwFHzHCPQrZDVbevvP545P4I08HCURKfGxPIkj6xMg2IZM1zu9SaIjBe2
    G4Pjc2bIY+TdSiQQAAAQEA3V1iVYTzoiYNVnLXgA+Uy+tArVg0eysNpsk/rofQOO+MRKmx
    lKnK7U5/n2O+daJIF0Ewl20cJCT10LEOXj994ok7kYd6NcQCVvL2bdptCLYCEqFiJ0skvJ
    4A41oWA+zKylXbwjDelxlUdAb0VTUVDovI1yBPqjn4C6AMj4M8sxzH/UGvV2ARwWWf4dFb
    T/PqNFCi4eVYKekmsS09UTEKioFzwJ1xj9Hsc5kIfUWBMZ0ZonZVqDj1/dGauf2WjXMQ7L
    zifVVC7UFFQkZU6xdzTe43kjyoO+TLQneYGP9YrIJhL91cDj7IjmIyjnC1b52+P+0z3cjN
    2Nla3GZTilzxBQAAAAl0ZWt0b24tY2k=
    -----END OPENSSH PRIVATE KEY-----
  known_hosts: |
    gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-bot
  namespace: tekton-ci
secrets:
  - name: gitlab-credentials