{
 "title": "Kubernetes Cluster Monitoring",
 "description": "This dashboard is one of major topic for Kubernetes Book and best optimized for virtual machine environment provided with https://github.com/sysnet4admin/_Book_k8sInfraNotice: It may be running on the other environment but cannot be guaranteed.",
 "tags": [
  "kubernetes",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name,cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kubelet_node_name{cluster=\"$cluster\"},kubernetes_io_hostname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_os_info{kubernetes_io_hostname=\"$node\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{node=\"$node\", cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "集群总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "Total CPU Cores"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU Requests"
    }
   ]
  },
  {
   "title": "CPU Requests(Utilization rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU Requests"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Limits (Utilization rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory Requests"
    }
   ]
  },
  {
   "title": "Memory Requests (Utilization rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory Requests"
    }
   ]
  },
  {
   "title": "Total Memory Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total Memory Limits"
    }
   ]
  },
  {
   "title": "Total Memory Limits (Utilization rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "节点资源",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kube_node_info{cluster=\"$cluster\"}",
     "legendFormat": "节点信息"
    },
    {
     "expr": "sum by(instance) (time() - node_boot_time_seconds{cluster=\"$cluster\"})",
     "legendFormat": "运行时间"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU limits"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory requests"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory limits"
    },
    {
     "expr": "label_replace(up{cluster=\"$cluster\", job=\"kubernetes-nodes\"}, \"node\", \"$1\", \"instance\", \"(.+)\")",
     "legendFormat": "运行状态"
    }
   ]
  },
  {
   "title": "节点总览：ALL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "节点 CPU 使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - avg by (kubernetes_io_hostname) (rate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\"} [$interval]))",
       "legendFormat": "{{kubernetes_io_hostname}} "
      }
     ]
    },
    {
     "title": "节点内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) ((node_memory_MemTotal_bytes{cluster=\"${cluster}\"} - (node_memory_MemFree_bytes{cluster=\"${cluster}\"} + node_memory_Buffers_bytes{cluster=\"${cluster}\"}+node_memory_Cached_bytes{cluster=\"${cluster}\"} )) / node_memory_MemTotal_bytes{cluster=\"${cluster}\"})",
       "legendFormat": "{{ kubernetes_io_hostname }}"
      }
     ]
    },
    {
     "title": "节点流量(in/out)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(node_network_receive_bytes_total{cluster=\"${cluster}\"}[1m]))",
       "legendFormat": "{{kubernetes_io_hostname}}_in[下载]"
      },
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(node_network_transmit_bytes_total{cluster=\"${cluster}\"}[1m]))",
       "legendFormat": "{{kubernetes_io_hostname}}_out[上传]"
      }
     ]
    },
    {
     "title": "节点硬盘使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname, mountpoint) (1-(node_filesystem_free_bytes{cluster=\"$cluster\",fstype=~\"xfs|ext4\", mountpoint!~\".*docker|.*kubelet\"}) / (node_filesystem_size_bytes{cluster=\"$cluster\", fstype=~\"xfs|ext4\", mountpoint!~\".*docker|.*kubelet\"}))",
       "legendFormat": "{{kubernetes_io_hostname}} {{mountpoint}}"
      }
     ]
    }
   ]
  },
  { "title": "节点详情：$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "node" },
  {
   "title": "总核数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{cluster=\"$cluster\",kubernetes_io_hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "总内存空间",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{cluster=\"$cluster\", kubernetes_io_hostname=\"$node\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",kubernetes_io_hostname=~\"$node\",mode=\"idle\"}[$interval])))",
     "legendFormat": "CPU 使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{kubernetes_io_hostname=~\"$node\"} / (node_memory_MemTotal_bytes{kubernetes_io_hostname=~\"$node\"})))",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(1 - (sum by (mountpoint) ((node_filesystem_free_bytes{kubernetes_io_hostname=~\"$node\",fstype=~\"xfs|ext.?\", mountpoint!~\".*docker.*|.*kubelet.*\"}) / (node_filesystem_size_bytes{kubernetes_io_hostname=~\"$node\",fstype=~\"xfs|ext.?\", mountpoint!~\".*docker.*|.*kubelet.*\"}))))",
     "legendFormat": "硬盘使用率({{ mountpoint }})"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{cluster=\"$cluster\", kubernetes_io_hostname=\"$node\"} - node_boot_time_seconds{cluster=\"$cluster\", kubernetes_io_hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "节点分区可用空间",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\",fstype=~\"ext.*|xfs\", mountpoint!~\".*docker|.*kubelet\"}-0"
    },
    {
     "expr": "1-((node_filesystem_free_bytes{kubernetes_io_hostname=~\"$node\", fstype=~\"xfs|ext.*\", mountpoint!~\".*docker|.*kubelet\"}) / (node_filesystem_size_bytes{kubernetes_io_hostname=~\"$node\", fstype=~\"xfs|ext4\", mountpoint!~\".*docker|.*kubelet\"}))"
    },
    {
     "expr": "node_filesystem_size_bytes{kubernetes_io_hostname=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint!~\".*docker|.*kubelet\"}-0",
     "legendFormat": "总量"
    }
   ]
  },
  {
   "title": "打开的文件描述符(左 )/每秒上下文切换次数(右)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "使用的文件描述符[左]"
    },
    {
     "expr": "irate(node_context_switches_total{kubernetes_io_hostname=~\"$node\"}[5m])",
     "legendFormat": "每秒上下文切换次数[右]"
    }
   ]
  },
  {
   "title": "节点 CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", kubernetes_io_hostname=\"$node\", mode=\"system\"}[$interval])) by (instance) * 100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{kubernetes_io_hostname=\"$node\",mode=\"user\"}[$interval])) by (instance) * 100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{kubernetes_io_hostname=\"$node\",mode=\"iowait\"}[$interval])) by (instance) * 100",
     "legendFormat": "磁盘 IO 使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{kubernetes_io_hostname=\"$node\", mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "1 分钟负载"
    },
    {
     "expr": "node_load5{kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "5 分钟负载"
    },
    {
     "expr": "node_load15{kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "15 分钟负载"
    }
   ]
  },
  {
   "title": "网络带宽(下载/上传)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\",kubernetes_io_hostname=~\"$node\",device=~\"eth.+\"}[$interval])*8",
     "legendFormat": "{{  device }}_下载"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{kubernetes_io_hostname=~\"$node\",device=~\"eth.+\"}[$interval])*8",
     "legendFormat": "{{  device }}_上传"
    }
   ]
  },
  {
   "title": "节点内存信息",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_io_hostname=~\"$node\"} - node_memory_MemAvailable_bytes{kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "使用内存"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "可用内存"
    }
   ]
  },
  {
   "title": "磁盘读写速率(IOPS)/每秒",
   "type": "timeseries",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{cluster=\"$cluster\",kubernetes_io_hostname=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{kubernetes_io_hostname=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Write"
    },
    {
     "expr": "node_disk_io_now{kubernetes_io_hostname=~\"$node\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "磁盘读写(容量)/每秒",
   "type": "timeseries",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{cluster=\"$cluster\",kubernetes_io_hostname=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{kubernetes_io_hostname=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Writte"
    }
   ]
  },
  {
   "title": "磁盘 IO 读写耗时/每秒",
   "type": "timeseries",
   "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}[$interval]) / rate(node_disk_reads_completed_total{cluster=\"$cluster\", instance=\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\"}[$interval]) / rate(node_disk_writes_completed_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "磁盘 (I/O Util)操作耗时占比/每秒",
   "type": "timeseries",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{cluster=\"$cluster\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_ IO 操作耗时(每秒)"
    }
   ]
  },
  {
   "title": "网络 Socket 连接数",
   "type": "timeseries",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$instance\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$instance\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$instance\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$instance\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "节点 Pod：$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kubelet_running_pods{cluster=\"$cluster\", kubernetes_io_hostname=\"$node\"}",
       "legendFormat": "Node Pods"
      }
     ]
    },
    {
     "title": "Pod Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kubelet_running_pods{cluster=\"$cluster\", kubernetes_io_hostname=\"$node\"}",
       "legendFormat": "Pod Running"
      }
     ]
    },
    {
     "title": "Pod Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", pod=~\"$pod\", phase=\"Succeeded\"})",
       "legendFormat": "Pod Succeeded"
      }
     ]
    },
    {
     "title": "Pod Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", pod=~\"$pod\", phase=\"Pending\"})",
       "legendFormat": "Pod Pending"
      }
     ]
    },
    {
     "title": "Pod Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", pod=~\"$pod\", phase=\"Failed\"})",
       "legendFormat": "Pod Failed"
      }
     ]
    },
    {
     "title": "Pod Unknown",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", pod=~\"$pod\", phase=\"Unknown\"})",
       "legendFormat": "Pod Unknown"
      }
     ]
    },
    {
     "title": "Pod CPU 使用率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 606 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", pod=~\"$pod\", container!=\"POD\"}[$interval])) by (pod, namespace) / (sum(container_spec_cpu_quota{cluster=\"$cluster\",pod=~\"$pod\", container!=\"POD\"}/100000) by (pod, namespace))",
       "legendFormat": "{{ namespace }} | {{ pod }}"
      }
     ]
    },
    {
     "title": "新面板",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 606 },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", pod=~\"$pod\", container!=\"POD\"}[$interval])) by (pod, namespace)",
       "legendFormat": "{{pod}} | CPU 使用核数"
      }
     ]
    },
    {
     "title": "Pod 内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 616 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"})",
       "legendFormat": "{{ namespace }} | {{ pod }} 内存限制"
      },
      {
       "expr": "sum by (namespace, pod) (container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"})",
       "legendFormat": "{{ namespace }} | {{ pod }}  已使用内存"
      },
      {
       "expr": "sum by (namespace, pod) (container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\", container!=\"POD\"}) / sum by (namespace, pod) (kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}) * 100",
       "legendFormat": "{{ namespace }} | {{ pod }} 内存使用率"
      }
     ]
    },
    {
     "title": "Pod 内存使用量",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 616 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"})",
       "legendFormat": "{{ namespace }} | {{ pod }}  已使用内存"
      }
     ]
    },
    {
     "title": "Pod 文件写入速率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 627 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", kubernetes_io_hostname=\"$node\", pod=~\"$pod\"}[$interval]))",
       "legendFormat": "{{ namespace }} | {{ pod }}"
      }
     ]
    },
    {
     "title": "Pod 卷存储",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 638 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pod_volume_storage_usage_bytes{cluster=\"$cluster\",  node=\"$node\"}",
       "legendFormat": "{{ namespace }} | {{ pod }} | {{ volume }}"
      }
     ]
    },
    {
     "title": "Pod 临时存储",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 649 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pod_ephemeral_storage_usage_bytes{cluster=\"$cluster\",  node=\"$node\"}",
       "legendFormat": "{{ namespace }} | {{ pod }}"
      }
     ]
    },
    {
     "title": "Pod 线程数",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 660 },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (container_threads{cluster=\"$cluster\", pod=~\"$pod\", container!=\"POD\"})",
       "legendFormat": "{{ namespace }} | {{ pod }} Thread"
      }
     ]
    },
    {
     "title": "Pod 网络带宽(下载/上传)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 671 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (rate(container_network_receive_bytes_total{cluster=\"$cluster\",pod=~\"$pod\", container!=\"\"}[$interval]))",
       "legendFormat": "{{ namespace }} | {{ pod }}_下载"
      },
      {
       "expr": "sum by (namespace, pod) (rate(container_network_transmit_bytes_total{pod=~\"$pod\", container!=\"\"}[$interval]))",
       "legendFormat": "{{ namespace }} | {{ pod }}_上传"
      }
     ]
    }
   ]
  }
 ]
}