{
 "title": "Kubernetets Pods Monitoring",
 "tags": [
  "pods",
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod!~\"rollback-user-data-.*\", cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "pod_ip",
    "label": "pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod!~\"rollback-user-data-.*\", cluster=\"$cluster\", pod=~\"$pod\"},pod_ip)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Pod 资源总览：$namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(count by (pod)(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"}))",
       "legendFormat": "Total Pods"
      }
     ]
    },
    {
     "title": "Pod Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", phase=\"Running\"})",
       "legendFormat": "Pod Running"
      }
     ]
    },
    {
     "title": "Pod Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", phase=\"Succeeded\"})",
       "legendFormat": "Pod Succeeded"
      }
     ]
    },
    {
     "title": "Pod Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", phase=\"Pending\"})",
       "legendFormat": "Pod Pending"
      }
     ]
    },
    {
     "title": "Pod Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", phase=\"Failed\"})",
       "legendFormat": "Pod Failed"
      }
     ]
    },
    {
     "title": "Pod Unknown",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", phase=\"Unknown\"})",
       "legendFormat": "Pod Unknown"
      }
     ]
    },
    {
     "title": "Pod 资源总览",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\", service=\"sls-kube-state-metrics\"}",
       "legendFormat": "Pod 信息"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"})",
       "legendFormat": "CPU limits"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"})",
       "legendFormat": "内存 limits"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"})",
       "legendFormat": "重启次数"
      },
      {
       "expr": "kube_pod_container_status_running{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"}",
       "legendFormat": "运行状态"
      },
      {
       "expr": "sum by (pod)(time()-kube_pod_start_time{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"})",
       "legendFormat": "运行时间"
      },
      {
       "expr": "sum by (pod) (time() - (container_start_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", container!=\"POD\",container!=\"\", pod!~\"rollback-user-data-.*\"}))",
       "legendFormat": "重启时间"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_status_waiting_reason{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"})",
       "legendFormat": "原因"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"})",
       "legendFormat": "CPU Requests"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", pod!~\"rollback-user-data-.*\"})",
       "legendFormat": "内存 Requests"
      }
     ]
    },
    {
     "title": "Pod CPU 使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}[$interval])) by (pod) / (sum(container_spec_cpu_quota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}/100000) by (pod))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod 内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}",
       "legendFormat": "{{ pod }} 内存限制"
      },
      {
       "expr": "container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}",
       "legendFormat": "{{ pod }}  已使用内存"
      },
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\", container!=\"POD\"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}) * 100",
       "legendFormat": "{{ pod }} 内存使用率"
      }
     ]
    },
    {
     "title": "Pod 线程数",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (container_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod!=\"\", container!=\"POD\"})",
       "legendFormat": "{{ pod }} Thread"
      }
     ]
    },
    {
     "title": "Pod 网络带宽(下载/上传)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\", pod!=\"\"}[$interval]))",
       "legendFormat": "{{ pod }}_下载"
      },
      {
       "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\", pod!=\"\"}[$interval]))",
       "legendFormat": "{{ pod }}_上传"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod 资源详情：$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod 运行时间",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "time()-kube_pod_start_time{cluster=\"$cluster\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Pod 重启次数",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Pod 资源分配",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\",pod=\"$pod\"})",
       "legendFormat": "CPU limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\",pod=\"$pod\"})",
       "legendFormat": "Memory limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\",pod=\"$pod\"})",
       "legendFormat": "CPU requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\",pod=\"$pod\"})",
       "legendFormat": "Memory requests"
      }
     ]
    },
    {
     "title": "Pos 资源使用",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (container) (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", container!=\"POD\"}) / sum by (container) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", container!=\"POD\"})",
       "legendFormat": "Memory Usage ({{ container }})"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}[$interval])) by (pod) / (sum(container_spec_cpu_quota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}/100000) by (pod))",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Pod CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}[$interval])) by (pod) / (sum(container_spec_cpu_quota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}/100000) by (pod)) * 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod 内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", container!=\"POD\"}) ",
       "legendFormat": "总内存"
      },
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", container!=\"POD\"}) ",
       "legendFormat": "已使用内存"
      },
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", container!=\"POD\"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", container!=\"POD\"})",
       "legendFormat": "内存使用率"
      }
     ]
    },
    {
     "title": "Pod 网络带宽(下载/上传)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$interval]))",
       "legendFormat": "下载"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$interval]))",
       "legendFormat": "上传"
      }
     ]
    },
    {
     "title": "Pod 线程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(container_threads{pod=\"$pod\", container!=\"POD\"})",
       "legendFormat": "Thread"
      }
     ]
    }
   ]
  }
 ]
}