{
 "title": "Kubernetes StatefulSet  Monitoring",
 "tags": [
  "prometheus",
  "kubernetes",
  "statefulset"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "statefulset",
    "label": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_labels{namespace=\"$namespace\", cluster=\"$cluster\"},statefulset)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$statefulset-\\\\d+\"},pod)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,3h,6h,12,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "资源总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (statefulset) (kube_statefulset_replicas{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"})",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Ready Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (statefulset) (kube_statefulset_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"})",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (statefulset) (kube_statefulset_status_replicas_current{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"})",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Update Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (statefulset) (kube_statefulset_status_replicas_updated{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"})",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Current Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (statefulset) (kube_statefulset_metadata_generation{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"})",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "资源总览",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Pod 信息"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU limits"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "内存 limits"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "重启次数"
    },
    {
     "expr": "kube_pod_container_status_running{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "运行状态"
    },
    {
     "expr": "sum by (pod)(time()-kube_pod_start_time{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "运行时间"
    },
    {
     "expr": "sum by (pod) (time() - (container_start_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\",container!=\"\"}))",
     "legendFormat": "最近一次重启时间"
    }
   ]
  },
  { "title": "Pod $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pod CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}[$interval])) by (pod) / (sum(container_spec_cpu_quota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}/100000) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod CPU 使用核数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}[$interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "PVC 存储",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pod 内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}",
     "legendFormat": "{{ pod }} 内存限制"
    },
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}",
     "legendFormat": "{{ pod }}  已使用内存"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\", container!=\"POD\"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}) * 100",
     "legendFormat": "{{ pod }} 内存使用率"
    }
   ]
  },
  {
   "title": "Pod 线程数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"})",
     "legendFormat": "{{ pod }} Thread"
    }
   ]
  },
  {
   "title": "Pod 网络流量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ pod }} in"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ pod }} out"
    }
   ]
  }
 ]
}