{
 "title": "Kubernetes Deployment Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name{cluster!~\"cw-.*\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\", cluster=\"$cluster\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,3h,6h,12,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "资源总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{cluster=\"$cluster\", namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Ready Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_ready{cluster=\"$cluster\",  namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{cluster=\"$cluster\",  namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Update Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_updated{cluster=\"$cluster\", namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Update Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_metadata_generation{cluster=\"$cluster\",namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "资源总览",
   "type": "table",
   "description": "查看 Pod  资源、镜像版本、运行状态和重启次数等指标",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (pod, container, image) (kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"gracefulshutdown\"})",
     "legendFormat": "镜像版本"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"gracefulshutdown\"})",
     "legendFormat": "CPU Limits"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"gracefulshutdown\"})",
     "legendFormat": "内存 Limits"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_status_running{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"gracefulshutdown\"})",
     "legendFormat": "运行状态"
    },
    {
     "expr": "sum by (pod, container) (time() - (container_start_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"POD\",container!=\"\", container!=\"gracefulshutdown\"}))",
     "legendFormat": "Pod 启动时间"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"gracefulshutdown\"})",
     "legendFormat": "重启次数"
    },
    {
     "expr": "kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\"}",
     "legendFormat": "Pod 信息"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"gracefulshutdown\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+\", container!=\"gracefulshutdown\"})",
     "legendFormat": "内存 Requests"
    }
   ]
  },
  { "title": "Pod $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pod CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}[$interval])) by (pod) / (sum(container_spec_cpu_quota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"}/100000) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod CPU 抑制率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval])\n)\n/\nsum by (pod) (\n  rate(container_cpu_cfs_periods_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval])\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod 内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}",
     "legendFormat": "{{ pod }} 内存限制"
    },
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}",
     "legendFormat": "{{ pod }}  已使用内存"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\", container!=\"POD\"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!~\"POD|gracefulshutdown\"}) * 100",
     "legendFormat": "{{ pod }} 内存使用率"
    }
   ]
  },
  {
   "title": "Pod 文件写速率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod 文件读速率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ namespace }} | {{ pod }} | 读速率"
    }
   ]
  },
  {
   "title": "Pod 卷存储",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, volume) (pod_volume_storage_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{ pod }} | {{ volume }}"
    }
   ]
  },
  {
   "title": "Pod 临时存储",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, volume) (pod_volume_storage_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{ pod }} | {{ volume }}"
    }
   ]
  },
  {
   "title": "Pod 线程数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"})",
     "legendFormat": "{{ pod }} Thread"
    }
   ]
  },
  {
   "title": "Pod 网络带宽(下载/上传)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ pod }}_下载"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ pod }}_上传"
    }
   ]
  }
 ]
}