apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.commany.com/springboot-deployment
    newTag: prod

replicas:
  - name: springboot-deployment
    count: 2

patchesStrategicMerge:
  - patch.yaml
