apiVersion: v1
kind: ServiceAccount
metadata:
  name: val-cluster-admin   # 既保留了平台辨识度，又直观体现了最高特权
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: val-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: val-cluster-admin
    namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: val-cluster-admin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: val-cluster-admin
type: kubernetes.io/service-account-token

# 获取 Admin Token
# kubectl get secret val-cluster-admin-token -n kube-system -o jsonpath={.data.token} | base64 -d