apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
type: Opaque
stringData:
  objstore.yml: |-
    type: ALIYUNOSS
    config:
      endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
      bucket: "thanos"
      access_key_id: "XXXXXXXX"
      access_key_secret: "XXXXXXXX"